### PR TITLE
Message: parse message replies

### PR DESCRIPTION
**Pull request by curioussavage**
:eyeglasses: @ajacksified

### CODE REVIEW

**Comment by curioussavage** [comment]
:haircut:

**Comment by curioussavage** [comment]
How about I set the replies field to an empty array in the model when it is a string? It would make adding replies when you respond a little easier

**Comment by ajacksified** [comment]
@curioussavage setting it as an array is fine. :nail_care: for that

**Comment by curioussavage** [comment]
:haircut:  done

**Comment by ajacksified** [comment]
:fish:

**Pull request closed without merging**
