### PR TITLE
Obey over_18 settings for link / search get

### PR DESCRIPTION
**Pull request by ajacksified**
:eyeglasses: @florenceyeun @Deimos

### CODE REVIEW

**Comment by Deimos** [comment]
I am horribly unqualified to be giving this :fish:

**Comment by ajacksified** [comment]
safe

**Comment by florenceyeun** [comment]
:fish: lgtm

**Comment by ajacksified** [comment]
@florenceyeun / @Deimos - had to revert this, because it was returning empty lists for NSFW subreddits.

**Pull request merged**
